import os
import subprocess
import asyncio
import logging

logger = logging.getLogger("GameHubNexus-ShaderCompiler")

class ShaderCompiler:
    def __init__(self):
        self.cache_dir = "/app/dxvk_caches"
        os.makedirs(self.cache_dir, exist_ok=True)
        
    async def compile(self, game_id: str, executable_path: str) -> str:
        """
        Runs the game executable headlessly in a virtual framebuffer (Xvfb) using Wine.
        Configures DXVK to output the compiled pipeline state cache (.dxvk-cache).
        """
        if not game_id or not executable_path:
            return ""
            
        cache_file_path = os.path.join(self.cache_dir, f"{game_id}.dxvk-cache")
        
        # Setup headless environment variables
        env = os.environ.copy()
        env["WINEPREFIX"] = f"/app/prefixes/prefix_shared" # Use a shared prefix
        env["WINEDEBUG"] = "-all"
        
        # DXVK Cache Configuration
        env["DXVK_STATE_CACHE"] = "1"
        env["DXVK_STATE_CACHE_PATH"] = self.cache_dir
        
        # DXVK environment looks for executable name to generate cache file: [executable_name].dxvk-cache
        executable_name = os.path.basename(executable_path)
        expected_cache_name = f"{executable_name}.dxvk-cache"
        expected_cache_path = os.path.join(self.cache_dir, expected_cache_name)
        
        logger.info(f"Starting headless compilation for {game_id}...")
        logger.info(f"Executing: xvfb-run -a wine {executable_path}")
        
        # Start game under Xvfb (Virtual display)
        # xvfb-run automatically manages an X server display for the program
        cmd = ["xvfb-run", "-a", "wine", executable_path]
        
        try:
            # Run the game process asynchronously
            process = await asyncio.create_subprocess_exec(
                *cmd,
                env=env,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE
            )
            
            # Let the game run headlessly for 60 seconds (enough to initialize menus and load intro shaders)
            logger.info("Game launched in headless background. Compiling shader pipelines...")
            await asyncio.sleep(60.0) 
            
            # Terminate the game process
            logger.info("Terminating headless game session...")
            try:
                process.terminate()
                await process.wait()
            except Exception as e:
                logger.error(f"Error terminating game process: {str(e)}")
                
            # Check if the cache file was generated
            if os.path.exists(expected_cache_path):
                # Rename to our standard game-id format
                shutil_rename = True
                try:
                    import shutil
                    shutil.move(expected_cache_path, cache_file_path)
                    logger.info(f"Shader cache compiled and saved at {cache_file_path}")
                    return cache_file_path
                except Exception as e:
                    logger.error(f"Failed to rename shader cache: {str(e)}")
            else:
                logger.warning("No DXVK state cache file was generated by the game run.")
                
        except Exception as e:
            logger.error(f"Shader compilation failed: {str(e)}")
            
        return ""
